apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-demo-chart.fullname" . }}
  labels:
    {{- include "nodejs-demo-chart.labels" . | nindent 4 }}
{{- if .Values.labels }}
  {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
  {{- end }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodejs-demo-chart.selectorLabels" . | nindent 6 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        {{- include "nodejs-demo-chart.selectorLabels" . | nindent 8 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
    spec:
      imagePullSecrets: 
      - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP