apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-demo-chart.fullname" . }}
spec:
  selector:
    {{- include "nodejs-demo-chart.selectorLabels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  